services:
  postgres:
    image: 'postgres:latest'
    command: ['postgres', '-c', 'wal_level=logical']
    tmpfs:
      - /var/lib/postgresql
    environment:
      - 'POSTGRES_DB=checkout-pulse'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d checkout-pulse" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

  # UI for Redis
  redis-commander:
    image: 'rediscommander/redis-commander:latest'
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  rabbitmq:
    image: 'rabbitmq:3-management'
    environment:
      - 'RABBITMQ_DEFAULT_USER=guest'
      - 'RABBITMQ_DEFAULT_PASS=guest'
    ports:
      - '5672:5672'
      - '15672:15672' # Management UI
    healthcheck:
      test: rabbitmq-diagnostics -q check_running
      interval: 5s
      timeout: 5s
      retries: 5



